services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: highloaddb
      POSTGRES_USER: highload_user
      POSTGRES_PASSWORD: highload_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
